// <auto-generated />
namespace BugTrackerV2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddTicketAction : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTicketAction));
        
        string IMigrationMetadata.Id
        {
            get { return "202011110917567_Add TicketAction"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
